# Generated by Django 3.1.6 on 2021-02-10 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=264)),
                ('lastname', models.CharField(max_length=264)),
                ('email', models.EmailField(max_length=264)),
            ],
        ),
    ]
