# Generated by Django 3.1.6 on 2021-02-12 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='fname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='users',
            name='firstname',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='firstapp.fname'),
        ),
    ]
