# Generated by Django 3.1.6 on 2021-02-12 11:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_auto_20210212_1637'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='users',
            new_name='userss',
        ),
    ]
