# Generated by Django 3.1.6 on 2021-02-12 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_auto_20210212_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userss',
            name='firstname',
            field=models.CharField(max_length=264),
        ),
    ]
